version: "2"
services:
  my-wpdb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wpdbpassword
    volumes:
      - ./_wpdata:/var/lib/mysql
    restart: always
    container_name:
      redirect-test-mysql
  my-wp:
    image: wordpress:4.7.3-php7.1-apache
    volumes:
      - ./_wp/:/var/www/html
    ports:
      - "80:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: wpdbpassword
    container_name:
      redirect-test-wp
volumes:
    db_data:
